CREATE TABLE raw_fifa_world_cup_2026_player_performance (
    player_id VARCHAR(6) PRIMARY KEY,
    player_name TEXT,
    age INT,
    nationality TEXT,
    team TEXT,
    jersey_number INT,
    position TEXT,
    height_cm INT,
    weight_kg INT,
    preferred_foot VARCHAR(5),
    club_name TEXT,
    market_value_eur INT,
    match_id VARCHAR(6),
    match_date DATE,
    stadium TEXT,
    city TEXT,
    opponent_team TEXT,
    tournament_stage TEXT,
    match_result VARCHAR(1),
    goals_team INT,
    goals_opponent INT,
    minutes_played INT,
    goals INT,
    assists INT,
    shots INT,
    shots_on_target INT,
    expected_goals_xg NUMERIC,
    expected_assists_xa NUMERIC,
    key_passes INT,
    successful_passes INT,
    total_passes INT,
    pass_accuracy NUMERIC,
    dribbles_attempted INT,
    successful_dribbles INT,
    crosses INT,
    successful_crosses INT,
    tackles INT,
    interceptions INT,
    clearances INT,
    blocks INT,
    aerial_duels_won INT,
    aerial_duels_lost INT,
    recoveries INT,
    defensive_actions INT,
    fouls_committed INT,
    fouls_suffered INT,
    yellow_cards INT,
    red_cards INT,
    offsides INT,
    saves INT,
    save_percentage NUMERIC,
    punches INT,
    clean_sheet INT,
    goals_conceded INT,
    penalty_saves INT,
    distance_covered_km NUMERIC,
    sprint_distance_km NUMERIC,
    top_speed_kmh NUMERIC,
    accelerations INT,
    decelerations INT,
    stamina_score NUMERIC,
    player_rating NUMERIC,
    performance_score NUMERIC,
    offensive_contribution NUMERIC,
    defensive_contribution NUMERIC,
    possession_impact NUMERIC,
    pressure_resistance NUMERIC,
    creativity_score NUMERIC,
    consistency_score NUMERIC,
    clutch_performance_score NUMERIC,
    total_goals_tournament INT,
    total_assists_tournament INT,
    total_minutes_tournament INT,
    player_of_match_awards INT,
    tournament_rating NUMERIC
);

ALTER TABLE public.raw_fifa_world_cup_2026_player_performance OWNER to postgres;

CREATE INDEX idx_player_id ON public.raw_fifa_world_cup_2026_player_performance (player_id);

-- multiple instances of same player, cannot use player_id as primary key; remove since we don't have any other tables.
ALTER TABLE 
    raw_fifa_world_cup_2026_player_performance 
DROP CONSTRAINT 
    raw_fifa_world_cup_2026_player_performance_pkey;